server:
  port: 8000

# Spring Boot Admin Serveré…ç½®
spring:
  boot:
    admin:
      monitor:
        status-lifetime: 100000
        status-interval: 100000
        default-timeout: 100000
      ui:
        external-views:
          - label: "ğŸš€"
            url: https://springboot.plus
            order: 2000

# Spring Boot Admin ç™»å½•è´¦å·å¯†ç 
spring-boot-plus:
  admin:
    username: admin
    password: admin
